version: '2'

services:
  pictshare:
    restart: always
    image: hascheksolutions/pictshare:latest
    volumes:
    - ./volumes/upload:/usr/share/nginx/html/upload
    ports:
    - "80:80"
    - "443:443"
    environment:
    - AUTOUPDATE=false
    - MAX_UPLOAD_SIZE=
    - TITLE=
    - PNG_COMPRESSION=
    - JPEG_COMPRESSION=
    - MASTER_DELETE_CODE=
    - MASTER_DELETE_IP=
    - UPLOAD_FORM_LOCATION=
    - LOW_PROFILE=
    - UPLOAD_CODE=
    - IMAGE_CHANGE_CODE=
    - LOG_UPLOADER=
    - MAX_RESIZED_IMAGES=
    - ALLOW_BLOATING=
    - FORCE_DOMAIN=
    - SHOW_ERRORS=
