version: '2'

services:
  pictshare:
    restart: always
    image: hascheksolutions/pictshare:latest
    volumes:
    - ./volumes/upload:/usr/share/nginx/html/upload
    ports:
    - "80:80"
    - "443:443"
    environment:
    - TITLE=
    - AUTOUPDATE=false
    - MAXUPLOADSIZE=
    - MASTERDELETECODE=
    - BLOATING=
    - UPLOADCODE=
    - UPLOADPATH=
    - IMAGECHANGECODE=
    - LOGUPLOADER=
    - MAXRESIZEDIMAGES=
    - DOMAIN=
    - SHOWERRORS=
